### ISSUE TITLE
Adding a date option to the query doesn't seem to work

### ISSUE THREAD

**Issue by braskinfvr** [james75/SolrMongoImporter#1]
Howdy,

I have played around with the configuration file and I can't seem to get Solr to send to MongoDB a query that includes an ISODate or a Date parameter. For example,
as a test this gets no errors but imports nothing:
query="{'updated_at':{'$gt': 'anything' }}"

this gives me an "Indexing failed. Rolled back all changes"  error in Solr:
query="{'updated_at':{'$gt': ISODate('2013-04-17 12:11') }}"

I can't figure out how to actually send a query with a valid date comparison to MongoDB. If you could help me that would be great.

Thanks!
B.

**Comment by james75** [comment]
Try something like

 {'updated_at'':{$gt:{$date:'2013-04-17 12:11'}}}
