### ISSUE TITLE
Is it multi-threaded ? I have around 8 million records to import

### ISSUE THREAD

**Issue by nitinsurana** [james75/SolrMongoImporter#15]
I'm confused between https://github.com/5missions/mongoSolrImporter and this project. Though the former is quite old but says it has multi-threading support and someone [here commented](http://stackoverflow.com/questions/21450555/steps-to-connect-mongodb-and-solr-using-dataimporthandler/28090368#comment64778772_21709405) that he has used the former and achieved 10x performance.

Could you please shed some light on the performance aspects related to large data import for this project, assuming that the mongo collections have flat data structure with max 10 fields.

**Comment by james75** [comment]
On looking I would seem that threading is supported by the DataImportHandler but I cant say I ever remember trying it. You should find for a single thread that this locally integrated imported provides best performance. Last import I did was about 1/2 million documents taking about 5mins however this obviously all depends on the size of your documents and the your systems performance. 
If you do decide to give it ago it would be very interesting to find out your results.
