### ISSUE TITLE
Can this work with Solr 4.4?

### ISSUE THREAD

**Issue by krantiparisa** [james75/SolrMongoImporter#4]
I am trying to point the ivy.xml file to solr 4.4.0 but when I try to do ant jar it's still pulling down the solr 3.6 jars

and also ant jar gives me the following error

srcdir "/space/git_space/SolrMongoImporter/${src.dir}" does not exist!

**Comment by james75** [comment]
The jar should be compatible with > 3.6/ Also the ant build has now been fixed.
