### ISSUE TITLE
Not working with Solr 4.x?

### ISSUE THREAD

**Issue by B0rner** [james75/SolrMongoImporter#5]
Hi,
I have tried your SolrMongoImporter on solr 4.4 with mongo-java dirver 2.10.1.
After following your docs, i restarted the tomcat (where solr resists) an started the first import (using the solr admin gui). 
But there was a error befor the import starts:
```
ERROR org.apache.solr.servlet.SolrDispatchFilter  ? null:org.apache.solr.handler.dataimport.DataImportHandlerException: 
Data Config problem: 
The processing instruction target matching "[xX][mM][lL]" is not allowed
```

Is there any idea, how to fix that?

**Comment by james75** [comment]
This points to a problem with your XML config this error is thrown by the SAX parser.
